import type { SeasonFormat } from './season-format'
import type { AdminSeasonEntry } from './season-admin'
export type Viewer = { email:string;role:'voter'|'operator'|'admin' }
export type PublicSeason = { format?:SeasonFormat;rulesVersion?:string;id:string;slug:string;name:string;status:'draft'|'published'|'live'|'completed'|'archived';isCurrent:boolean;startsAt:string|null;endsAt:string|null;championCharacterId:string|null;championName?:string|null;championGame?:string|null;championArtworkKey?:string|null;announcement:string;historyUnlocked:boolean }
export type PublicMatch = { id:string;groupCode:string|null;bracketPosition:number|null;leftVotes:number;rightVotes:number;status:'scheduled'|'live'|'closed'|'review';winnerCharacterId:string|null;roundId:string;stage:'swiss'|'knockout';roundNumber:number;roundName:string;startsAt:string;endsAt:string;leftId:string;leftName:string;leftGame:string;leftArtworkKey?:string|null;leftAvatarArtworkKey?:string|null;rightId:string;rightName:string;rightGame:string;rightArtworkKey?:string|null;rightAvatarArtworkKey?:string|null }
export type PublicCharacter = { id:string;name:string;game:string;summary:string;groupCode:string;seed:number;galleryArtworkKey:string|null;matchArtworkKey:string|null;avatarArtworkKey:string|null }
export type VoteSelection = { matchId:string;characterId:string;riskStatus:'approved'|'pending'|'rejected'|'revoked';createdAt:string }
export type VoteChoice = { matchId:string;characterId:string }
export type VoteResult = { status:'counted'|'under_review'|'already_voted';selection:VoteSelection;scores:{leftVotes:number;rightVotes:number} }
export type PublicRound = { id:string;stage:'swiss'|'knockout';roundNumber:number;name:string;startsAt:string;endsAt:string;status:'scheduled'|'live'|'closed'|'archived' }
export type PublicStanding = { groupCode:string;id:string;name:string;game:string;seed:number;avatarArtworkKey?:string|null;points:number;voteDifference:number;opponentPoints:number }
export type PublicOverview = { season:PublicSeason|null;previousSeason:PublicSeason|null;round:PublicRound|null;matches:PublicMatch[];siteAnnouncement:string;seasonAnnouncement:string }

export function apiErrorMessage(error:unknown,fallback='请求暂时失败，请稍后重试') {
  if(typeof error==='string')return error
  if(error&&typeof error==='object'){
    const detail=error as {name?:unknown;message?:unknown}
    if(detail.name==='ZodError')return'请求格式不正确，请刷新页面后重试'
    if(typeof detail.message==='string'&&detail.message)return detail.message
  }
  return fallback
}

async function request<T>(path:string,init?:RequestInit):Promise<T> {
  const response=await fetch(path,{credentials:'include',headers:{'content-type':'application/json',...(init?.headers??{})},...init})
  const body=await response.json().catch(()=>({})) as T&{error?:unknown}
  if(!response.ok)throw new Error(apiErrorMessage(body.error))
  return body
}
const seasonQuery=(slug?:string)=>slug?`?season=${encodeURIComponent(slug)}`:''

export const api={
  setSeasonAutomation:(id:string,enabled:boolean,reason:string)=>request<{ok:true}>(`/api/admin/seasons/${id}/automation`,{method:'PUT',body:JSON.stringify({enabled,reason})}),
  seasonConfiguration:(id:string)=>request<{format:SeasonFormat;entries:AdminSeasonEntry[];rounds:PublicRound[];validation:{valid:boolean;error:string|null}}>(`/api/admin/seasons/${id}/configuration`),
  saveSeasonConfiguration:(id:string,input:{format:SeasonFormat;startsAt:string;reason:string})=>request<{ok:true}>(`/api/admin/seasons/${id}/configuration`,{method:'PUT',body:JSON.stringify(input)}),
  importSeasonRoster:(id:string,entries:AdminSeasonEntry[],reason:string)=>request<{ok:true}>(`/api/admin/seasons/${id}/roster`,{method:'PUT',body:JSON.stringify({entries,reason})}),
  simulateSeason:(id:string)=>request<{simulation:{roundMatchCounts:number[];championId:string;uniqueParticipants:number};notice:string}>(`/api/admin/seasons/${id}/simulation`),
  saveSeasonSchedule:(id:string,rounds:Array<{id:string;startsAt:string;endsAt:string}>,reason:string)=>request<{ok:true}>(`/api/admin/seasons/${id}/schedule`,{method:'PUT',body:JSON.stringify({rounds,reason})}),
  me:()=>request<{user:Viewer|null}>('/api/auth/me'),requestCode:(email:string,turnstileToken?:string)=>request<{ok:true;expiresInSeconds:number;developmentCode?:string}>('/api/auth/request-code',{method:'POST',body:JSON.stringify({email,turnstileToken})}),verifyCode:(email:string,code:string)=>request<{ok:true;user:Viewer}>('/api/auth/verify-code',{method:'POST',body:JSON.stringify({email,code})}),logout:()=>request<{ok:true}>('/api/auth/logout',{method:'POST'}),
  publicOverview:()=>request<PublicOverview>('/api/public/overview'),publicSeasons:()=>request<{seasons:PublicSeason[]}>('/api/public/seasons'),publicSeason:(slug:string)=>request<{season:PublicSeason}>(`/api/public/seasons/${slug}`),publicMatches:(slug?:string)=>request<{matches:PublicMatch[]}>(`/api/public/matches${seasonQuery(slug)}`),publicRounds:(slug?:string)=>request<{rounds:PublicRound[]}>(`/api/public/rounds${seasonQuery(slug)}`),publicStandings:(slug?:string)=>request<{standings:PublicStanding[]}>(`/api/public/standings${seasonQuery(slug)}`),publicCharacters:(slug?:string)=>request<{characters:PublicCharacter[]}>(`/api/public/characters${seasonQuery(slug)}`),
  myVotes:(slug?:string)=>request<{votes:VoteSelection[]}>(`/api/votes/mine${seasonQuery(slug)}`),vote:(choices:VoteChoice[],deviceFingerprint?:string)=>request<{ok:true;votes:VoteResult[]}>('/api/votes',{method:'POST',body:JSON.stringify({choices,deviceFingerprint})}),dashboard:()=>request<{pendingVotes:number;activeMatches:number}>('/api/admin/dashboard'),adminMatches:()=>request<{matches:Array<{id:string;groupCode:string;leftName:string;rightName:string;leftVotes:number;rightVotes:number;status:string}>}>('/api/admin/matches'),riskVotes:()=>request<{votes:Array<{id:string;matchId:string;characterId:string;createdAt:string;email:string}>}>('/api/admin/risk/votes'),updateMatch:(matchId:string,input:{status?:string;leftVotes?:number;rightVotes?:number;reason:string})=>request<{ok:true}>(`/api/admin/matches/${matchId}`,{method:'PATCH',body:JSON.stringify(input)}),reviewRiskVote:(voteId:string,action:'approve'|'reject'|'revoke',reason:string)=>request<{ok:true}>(`/api/admin/risk/votes/${voteId}`,{method:'POST',body:JSON.stringify({action,reason})}),
  tournament:()=>request<{season:PublicSeason;settings:Record<string,string>;rounds:Array<{id:string;name:string;status:string;startsAt:string;endsAt:string}>;artwork:Array<{status:string;count:number}>}>('/api/admin/tournament'),adminSeasons:()=>request<{seasons:PublicSeason[]}>('/api/admin/seasons'),seasonEntries:(seasonId:string)=>request<{entries:Array<{characterId:string;groupCode:string;seed:number;name:string;game:string}>}>(`/api/admin/seasons/${seasonId}/entries`),updateSeasonEntry:(seasonId:string,characterId:string,input:{groupCode:string;seed:number;reason:string})=>request<{ok:true}>(`/api/admin/seasons/${seasonId}/entries/${characterId}`,{method:'PATCH',body:JSON.stringify(input)}),createSeason:(input:{name:string;slug?:string;startsAt:string;copyFromSeasonId?:string;reason:string})=>request<{ok:true;seasonId:string;slug:string}>('/api/admin/seasons',{method:'POST',body:JSON.stringify(input)}),seasonAction:(seasonId:string,action:'publish'|'archive'|'unlock-history'|'lock-history',reason:string)=>request<{ok:true}>(`/api/admin/seasons/${seasonId}/action`,{method:'POST',body:JSON.stringify({action,reason})}),updateSeason:(seasonId:string,input:{name?:string;announcement?:string;reason:string})=>request<{ok:true}>(`/api/admin/seasons/${seasonId}`,{method:'PATCH',body:JSON.stringify(input)}),controlTournament:(input:{action:'start-now'|'pause'|'resume'|'close'|'publish-schedule'|'lock-roster'|'unlock-roster';roundId?:string;scheduledStartAt?:string;reason:string})=>request<{ok:true}>('/api/admin/tournament/control',{method:'POST',body:JSON.stringify(input)}),updateSetting:(key:string,value:string,reason:string)=>request<{ok:true}>(`/api/admin/settings/${key}`,{method:'PUT',body:JSON.stringify({value,reason})}),
  characters:()=>request<{characters:Array<{id:string;name:string;game:string;summary:string;groupCode:string;seed:number;artworkSourceUrl:string|null;artworkSourceType:string;artworkQualityStatus:string;artworkFocusX:number;artworkFocusY:number}>}>('/api/admin/characters'),character:(id:string)=>request<{character:unknown}>(`/api/admin/characters/${id}`),updateCharacter:(id:string,input:Record<string,unknown>)=>request<{ok:true}>(`/api/admin/characters/${id}`,{method:'PATCH',body:JSON.stringify(input)}),localData:(action:'clear-votes'|'simulate-round'|'reset',reason:string)=>request<{ok:true}>('/api/admin/local-data',{method:'POST',body:JSON.stringify({action,reason})}),
  artwork:async(id:string,data:FormData)=>{const response=await fetch(`/api/admin/characters/${id}/artwork`,{method:'POST',credentials:'include',body:data});const body=await response.json().catch(()=>({})) as {ok?:boolean;error?:string};if(!response.ok)throw new Error(body.error??'素材上传失败');return body as {ok:true;keys:Record<string,string>;character:Record<string,unknown>}},deleteArtwork:(id:string,reason:string)=>request<{ok:true}>(`/api/admin/characters/${id}/artwork`,{method:'DELETE',body:JSON.stringify({reason})})
}
export function browserFingerprint(){return[navigator.userAgent,navigator.language,screen.width,screen.height,Intl.DateTimeFormat().resolvedOptions().timeZone].join('|')}
