#!/usr/bin/env bash
set -euo pipefail
npx wrangler r2 object put fumoe-2026-assets/characters/c001/avatar.webp --file=assets/processed/characters/c001/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c001/gallery.webp --file=assets/processed/characters/c001/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c001/match.webp --file=assets/processed/characters/c001/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c002/avatar.webp --file=assets/processed/characters/c002/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c002/gallery.webp --file=assets/processed/characters/c002/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c002/match.webp --file=assets/processed/characters/c002/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c003/avatar.webp --file=assets/processed/characters/c003/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c003/gallery.webp --file=assets/processed/characters/c003/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c003/match.webp --file=assets/processed/characters/c003/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c004/avatar.webp --file=assets/processed/characters/c004/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c004/gallery.webp --file=assets/processed/characters/c004/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c004/match.webp --file=assets/processed/characters/c004/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c005/avatar.webp --file=assets/processed/characters/c005/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c005/gallery.webp --file=assets/processed/characters/c005/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c005/match.webp --file=assets/processed/characters/c005/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c006/avatar.webp --file=assets/processed/characters/c006/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c006/gallery.webp --file=assets/processed/characters/c006/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c006/match.webp --file=assets/processed/characters/c006/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c007/avatar.webp --file=assets/processed/characters/c007/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c007/gallery.webp --file=assets/processed/characters/c007/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c007/match.webp --file=assets/processed/characters/c007/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c008/avatar.webp --file=assets/processed/characters/c008/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c008/gallery.webp --file=assets/processed/characters/c008/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c008/match.webp --file=assets/processed/characters/c008/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c009/avatar.webp --file=assets/processed/characters/c009/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c009/gallery.webp --file=assets/processed/characters/c009/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c009/match.webp --file=assets/processed/characters/c009/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c010/avatar.webp --file=assets/processed/characters/c010/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c010/gallery.webp --file=assets/processed/characters/c010/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c010/match.webp --file=assets/processed/characters/c010/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c011/avatar.webp --file=assets/processed/characters/c011/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c011/gallery.webp --file=assets/processed/characters/c011/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c011/match.webp --file=assets/processed/characters/c011/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c012/avatar.webp --file=assets/processed/characters/c012/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c012/gallery.webp --file=assets/processed/characters/c012/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c012/match.webp --file=assets/processed/characters/c012/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c013/avatar.webp --file=assets/processed/characters/c013/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c013/gallery.webp --file=assets/processed/characters/c013/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c013/match.webp --file=assets/processed/characters/c013/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c014/avatar.webp --file=assets/processed/characters/c014/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c014/gallery.webp --file=assets/processed/characters/c014/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c014/match.webp --file=assets/processed/characters/c014/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c015/avatar.webp --file=assets/processed/characters/c015/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c015/gallery.webp --file=assets/processed/characters/c015/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c015/match.webp --file=assets/processed/characters/c015/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c016/avatar.webp --file=assets/processed/characters/c016/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c016/gallery.webp --file=assets/processed/characters/c016/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c016/match.webp --file=assets/processed/characters/c016/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c017/avatar.webp --file=assets/processed/characters/c017/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c017/gallery.webp --file=assets/processed/characters/c017/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c017/match.webp --file=assets/processed/characters/c017/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c018/avatar.webp --file=assets/processed/characters/c018/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c018/gallery.webp --file=assets/processed/characters/c018/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c018/match.webp --file=assets/processed/characters/c018/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c019/avatar.webp --file=assets/processed/characters/c019/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c019/gallery.webp --file=assets/processed/characters/c019/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c019/match.webp --file=assets/processed/characters/c019/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c020/avatar.webp --file=assets/processed/characters/c020/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c020/gallery.webp --file=assets/processed/characters/c020/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c020/match.webp --file=assets/processed/characters/c020/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c021/avatar.webp --file=assets/processed/characters/c021/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c021/gallery.webp --file=assets/processed/characters/c021/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c021/match.webp --file=assets/processed/characters/c021/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c022/avatar.webp --file=assets/processed/characters/c022/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c022/gallery.webp --file=assets/processed/characters/c022/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c022/match.webp --file=assets/processed/characters/c022/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c023/avatar.webp --file=assets/processed/characters/c023/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c023/gallery.webp --file=assets/processed/characters/c023/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c023/match.webp --file=assets/processed/characters/c023/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c024/avatar.webp --file=assets/processed/characters/c024/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c024/gallery.webp --file=assets/processed/characters/c024/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c024/match.webp --file=assets/processed/characters/c024/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c025/avatar.webp --file=assets/processed/characters/c025/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c025/gallery.webp --file=assets/processed/characters/c025/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c025/match.webp --file=assets/processed/characters/c025/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c026/avatar.webp --file=assets/processed/characters/c026/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c026/gallery.webp --file=assets/processed/characters/c026/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c026/match.webp --file=assets/processed/characters/c026/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c027/avatar.webp --file=assets/processed/characters/c027/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c027/gallery.webp --file=assets/processed/characters/c027/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c027/match.webp --file=assets/processed/characters/c027/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c028/avatar.webp --file=assets/processed/characters/c028/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c028/gallery.webp --file=assets/processed/characters/c028/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c028/match.webp --file=assets/processed/characters/c028/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c029/avatar.webp --file=assets/processed/characters/c029/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c029/gallery.webp --file=assets/processed/characters/c029/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c029/match.webp --file=assets/processed/characters/c029/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c030/avatar.webp --file=assets/processed/characters/c030/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c030/gallery.webp --file=assets/processed/characters/c030/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c030/match.webp --file=assets/processed/characters/c030/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c031/avatar.webp --file=assets/processed/characters/c031/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c031/gallery.webp --file=assets/processed/characters/c031/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c031/match.webp --file=assets/processed/characters/c031/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c032/avatar.webp --file=assets/processed/characters/c032/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c032/gallery.webp --file=assets/processed/characters/c032/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c032/match.webp --file=assets/processed/characters/c032/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c033/avatar.webp --file=assets/processed/characters/c033/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c033/gallery.webp --file=assets/processed/characters/c033/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c033/match.webp --file=assets/processed/characters/c033/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c034/avatar.webp --file=assets/processed/characters/c034/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c034/gallery.webp --file=assets/processed/characters/c034/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c034/match.webp --file=assets/processed/characters/c034/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c035/avatar.webp --file=assets/processed/characters/c035/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c035/gallery.webp --file=assets/processed/characters/c035/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c035/match.webp --file=assets/processed/characters/c035/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c036/avatar.webp --file=assets/processed/characters/c036/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c036/gallery.webp --file=assets/processed/characters/c036/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c036/match.webp --file=assets/processed/characters/c036/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c037/avatar.webp --file=assets/processed/characters/c037/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c037/gallery.webp --file=assets/processed/characters/c037/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c037/match.webp --file=assets/processed/characters/c037/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c038/avatar.webp --file=assets/processed/characters/c038/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c038/gallery.webp --file=assets/processed/characters/c038/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c038/match.webp --file=assets/processed/characters/c038/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c039/avatar.webp --file=assets/processed/characters/c039/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c039/gallery.webp --file=assets/processed/characters/c039/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c039/match.webp --file=assets/processed/characters/c039/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c040/avatar.webp --file=assets/processed/characters/c040/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c040/gallery.webp --file=assets/processed/characters/c040/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c040/match.webp --file=assets/processed/characters/c040/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c041/avatar.webp --file=assets/processed/characters/c041/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c041/gallery.webp --file=assets/processed/characters/c041/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c041/match.webp --file=assets/processed/characters/c041/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c042/avatar.webp --file=assets/processed/characters/c042/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c042/gallery.webp --file=assets/processed/characters/c042/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c042/match.webp --file=assets/processed/characters/c042/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c043/avatar.webp --file=assets/processed/characters/c043/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c043/gallery.webp --file=assets/processed/characters/c043/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c043/match.webp --file=assets/processed/characters/c043/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c044/avatar.webp --file=assets/processed/characters/c044/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c044/gallery.webp --file=assets/processed/characters/c044/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c044/match.webp --file=assets/processed/characters/c044/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c045/avatar.webp --file=assets/processed/characters/c045/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c045/gallery.webp --file=assets/processed/characters/c045/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c045/match.webp --file=assets/processed/characters/c045/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c046/avatar.webp --file=assets/processed/characters/c046/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c046/gallery.webp --file=assets/processed/characters/c046/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c046/match.webp --file=assets/processed/characters/c046/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c047/avatar.webp --file=assets/processed/characters/c047/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c047/gallery.webp --file=assets/processed/characters/c047/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c047/match.webp --file=assets/processed/characters/c047/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c048/avatar.webp --file=assets/processed/characters/c048/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c048/gallery.webp --file=assets/processed/characters/c048/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c048/match.webp --file=assets/processed/characters/c048/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c049/avatar.webp --file=assets/processed/characters/c049/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c049/gallery.webp --file=assets/processed/characters/c049/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c049/match.webp --file=assets/processed/characters/c049/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c050/avatar.webp --file=assets/processed/characters/c050/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c050/gallery.webp --file=assets/processed/characters/c050/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c050/match.webp --file=assets/processed/characters/c050/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c051/avatar.webp --file=assets/processed/characters/c051/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c051/gallery.webp --file=assets/processed/characters/c051/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c051/match.webp --file=assets/processed/characters/c051/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c052/avatar.webp --file=assets/processed/characters/c052/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c052/gallery.webp --file=assets/processed/characters/c052/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c052/match.webp --file=assets/processed/characters/c052/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c053/avatar.webp --file=assets/processed/characters/c053/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c053/gallery.webp --file=assets/processed/characters/c053/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c053/match.webp --file=assets/processed/characters/c053/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c054/avatar.webp --file=assets/processed/characters/c054/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c054/gallery.webp --file=assets/processed/characters/c054/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c054/match.webp --file=assets/processed/characters/c054/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c055/avatar.webp --file=assets/processed/characters/c055/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c055/gallery.webp --file=assets/processed/characters/c055/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c055/match.webp --file=assets/processed/characters/c055/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c056/avatar.webp --file=assets/processed/characters/c056/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c056/gallery.webp --file=assets/processed/characters/c056/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c056/match.webp --file=assets/processed/characters/c056/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c057/avatar.webp --file=assets/processed/characters/c057/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c057/gallery.webp --file=assets/processed/characters/c057/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c057/match.webp --file=assets/processed/characters/c057/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c058/avatar.webp --file=assets/processed/characters/c058/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c058/gallery.webp --file=assets/processed/characters/c058/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c058/match.webp --file=assets/processed/characters/c058/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c059/avatar.webp --file=assets/processed/characters/c059/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c059/gallery.webp --file=assets/processed/characters/c059/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c059/match.webp --file=assets/processed/characters/c059/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c060/avatar.webp --file=assets/processed/characters/c060/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c060/gallery.webp --file=assets/processed/characters/c060/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c060/match.webp --file=assets/processed/characters/c060/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c061/avatar.webp --file=assets/processed/characters/c061/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c061/gallery.webp --file=assets/processed/characters/c061/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c061/match.webp --file=assets/processed/characters/c061/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c062/avatar.webp --file=assets/processed/characters/c062/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c062/gallery.webp --file=assets/processed/characters/c062/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c062/match.webp --file=assets/processed/characters/c062/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c063/avatar.webp --file=assets/processed/characters/c063/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c063/gallery.webp --file=assets/processed/characters/c063/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c063/match.webp --file=assets/processed/characters/c063/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c064/avatar.webp --file=assets/processed/characters/c064/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c064/gallery.webp --file=assets/processed/characters/c064/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c064/match.webp --file=assets/processed/characters/c064/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c065/avatar.webp --file=assets/processed/characters/c065/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c065/gallery.webp --file=assets/processed/characters/c065/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c065/match.webp --file=assets/processed/characters/c065/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c066/avatar.webp --file=assets/processed/characters/c066/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c066/gallery.webp --file=assets/processed/characters/c066/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c066/match.webp --file=assets/processed/characters/c066/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c067/avatar.webp --file=assets/processed/characters/c067/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c067/gallery.webp --file=assets/processed/characters/c067/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c067/match.webp --file=assets/processed/characters/c067/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c068/avatar.webp --file=assets/processed/characters/c068/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c068/gallery.webp --file=assets/processed/characters/c068/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c068/match.webp --file=assets/processed/characters/c068/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c069/avatar.webp --file=assets/processed/characters/c069/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c069/gallery.webp --file=assets/processed/characters/c069/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c069/match.webp --file=assets/processed/characters/c069/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c070/avatar.webp --file=assets/processed/characters/c070/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c070/gallery.webp --file=assets/processed/characters/c070/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c070/match.webp --file=assets/processed/characters/c070/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c071/avatar.webp --file=assets/processed/characters/c071/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c071/gallery.webp --file=assets/processed/characters/c071/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c071/match.webp --file=assets/processed/characters/c071/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c072/avatar.webp --file=assets/processed/characters/c072/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c072/gallery.webp --file=assets/processed/characters/c072/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c072/match.webp --file=assets/processed/characters/c072/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c073/avatar.webp --file=assets/processed/characters/c073/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c073/gallery.webp --file=assets/processed/characters/c073/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c073/match.webp --file=assets/processed/characters/c073/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c074/avatar.webp --file=assets/processed/characters/c074/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c074/gallery.webp --file=assets/processed/characters/c074/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c074/match.webp --file=assets/processed/characters/c074/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c075/avatar.webp --file=assets/processed/characters/c075/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c075/gallery.webp --file=assets/processed/characters/c075/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c075/match.webp --file=assets/processed/characters/c075/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c076/avatar.webp --file=assets/processed/characters/c076/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c076/gallery.webp --file=assets/processed/characters/c076/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c076/match.webp --file=assets/processed/characters/c076/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c077/avatar.webp --file=assets/processed/characters/c077/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c077/gallery.webp --file=assets/processed/characters/c077/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c077/match.webp --file=assets/processed/characters/c077/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c078/avatar.webp --file=assets/processed/characters/c078/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c078/gallery.webp --file=assets/processed/characters/c078/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c078/match.webp --file=assets/processed/characters/c078/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c079/avatar.webp --file=assets/processed/characters/c079/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c079/gallery.webp --file=assets/processed/characters/c079/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c079/match.webp --file=assets/processed/characters/c079/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c080/avatar.webp --file=assets/processed/characters/c080/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c080/gallery.webp --file=assets/processed/characters/c080/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c080/match.webp --file=assets/processed/characters/c080/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c081/avatar.webp --file=assets/processed/characters/c081/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c081/gallery.webp --file=assets/processed/characters/c081/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c081/match.webp --file=assets/processed/characters/c081/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c082/avatar.webp --file=assets/processed/characters/c082/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c082/gallery.webp --file=assets/processed/characters/c082/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c082/match.webp --file=assets/processed/characters/c082/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c083/avatar.webp --file=assets/processed/characters/c083/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c083/gallery.webp --file=assets/processed/characters/c083/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c083/match.webp --file=assets/processed/characters/c083/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c084/avatar.webp --file=assets/processed/characters/c084/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c084/gallery.webp --file=assets/processed/characters/c084/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c084/match.webp --file=assets/processed/characters/c084/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c085/avatar.webp --file=assets/processed/characters/c085/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c085/gallery.webp --file=assets/processed/characters/c085/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c085/match.webp --file=assets/processed/characters/c085/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c086/avatar.webp --file=assets/processed/characters/c086/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c086/gallery.webp --file=assets/processed/characters/c086/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c086/match.webp --file=assets/processed/characters/c086/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c087/avatar.webp --file=assets/processed/characters/c087/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c087/gallery.webp --file=assets/processed/characters/c087/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c087/match.webp --file=assets/processed/characters/c087/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c088/avatar.webp --file=assets/processed/characters/c088/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c088/gallery.webp --file=assets/processed/characters/c088/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c088/match.webp --file=assets/processed/characters/c088/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c089/avatar.webp --file=assets/processed/characters/c089/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c089/gallery.webp --file=assets/processed/characters/c089/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c089/match.webp --file=assets/processed/characters/c089/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c090/avatar.webp --file=assets/processed/characters/c090/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c090/gallery.webp --file=assets/processed/characters/c090/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c090/match.webp --file=assets/processed/characters/c090/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c091/avatar.webp --file=assets/processed/characters/c091/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c091/gallery.webp --file=assets/processed/characters/c091/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c091/match.webp --file=assets/processed/characters/c091/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c092/avatar.webp --file=assets/processed/characters/c092/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c092/gallery.webp --file=assets/processed/characters/c092/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c092/match.webp --file=assets/processed/characters/c092/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c093/avatar.webp --file=assets/processed/characters/c093/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c093/gallery.webp --file=assets/processed/characters/c093/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c093/match.webp --file=assets/processed/characters/c093/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c094/avatar.webp --file=assets/processed/characters/c094/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c094/gallery.webp --file=assets/processed/characters/c094/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c094/match.webp --file=assets/processed/characters/c094/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c095/avatar.webp --file=assets/processed/characters/c095/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c095/gallery.webp --file=assets/processed/characters/c095/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c095/match.webp --file=assets/processed/characters/c095/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c096/avatar.webp --file=assets/processed/characters/c096/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c096/gallery.webp --file=assets/processed/characters/c096/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c096/match.webp --file=assets/processed/characters/c096/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c097/avatar.webp --file=assets/processed/characters/c097/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c097/gallery.webp --file=assets/processed/characters/c097/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c097/match.webp --file=assets/processed/characters/c097/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c098/avatar.webp --file=assets/processed/characters/c098/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c098/gallery.webp --file=assets/processed/characters/c098/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c098/match.webp --file=assets/processed/characters/c098/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c099/avatar.webp --file=assets/processed/characters/c099/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c099/gallery.webp --file=assets/processed/characters/c099/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c099/match.webp --file=assets/processed/characters/c099/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c100/avatar.webp --file=assets/processed/characters/c100/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c100/gallery.webp --file=assets/processed/characters/c100/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c100/match.webp --file=assets/processed/characters/c100/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c101/avatar.webp --file=assets/processed/characters/c101/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c101/gallery.webp --file=assets/processed/characters/c101/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c101/match.webp --file=assets/processed/characters/c101/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c102/avatar.webp --file=assets/processed/characters/c102/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c102/gallery.webp --file=assets/processed/characters/c102/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c102/match.webp --file=assets/processed/characters/c102/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c103/avatar.webp --file=assets/processed/characters/c103/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c103/gallery.webp --file=assets/processed/characters/c103/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c103/match.webp --file=assets/processed/characters/c103/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c104/avatar.webp --file=assets/processed/characters/c104/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c104/gallery.webp --file=assets/processed/characters/c104/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c104/match.webp --file=assets/processed/characters/c104/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c105/avatar.webp --file=assets/processed/characters/c105/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c105/gallery.webp --file=assets/processed/characters/c105/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c105/match.webp --file=assets/processed/characters/c105/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c106/avatar.webp --file=assets/processed/characters/c106/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c106/gallery.webp --file=assets/processed/characters/c106/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c106/match.webp --file=assets/processed/characters/c106/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c107/avatar.webp --file=assets/processed/characters/c107/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c107/gallery.webp --file=assets/processed/characters/c107/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c107/match.webp --file=assets/processed/characters/c107/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c108/avatar.webp --file=assets/processed/characters/c108/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c108/gallery.webp --file=assets/processed/characters/c108/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c108/match.webp --file=assets/processed/characters/c108/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c109/avatar.webp --file=assets/processed/characters/c109/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c109/gallery.webp --file=assets/processed/characters/c109/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c109/match.webp --file=assets/processed/characters/c109/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c110/avatar.webp --file=assets/processed/characters/c110/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c110/gallery.webp --file=assets/processed/characters/c110/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c110/match.webp --file=assets/processed/characters/c110/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c111/avatar.webp --file=assets/processed/characters/c111/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c111/gallery.webp --file=assets/processed/characters/c111/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c111/match.webp --file=assets/processed/characters/c111/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c112/avatar.webp --file=assets/processed/characters/c112/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c112/gallery.webp --file=assets/processed/characters/c112/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c112/match.webp --file=assets/processed/characters/c112/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c113/avatar.webp --file=assets/processed/characters/c113/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c113/gallery.webp --file=assets/processed/characters/c113/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c113/match.webp --file=assets/processed/characters/c113/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c114/avatar.webp --file=assets/processed/characters/c114/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c114/gallery.webp --file=assets/processed/characters/c114/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c114/match.webp --file=assets/processed/characters/c114/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c115/avatar.webp --file=assets/processed/characters/c115/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c115/gallery.webp --file=assets/processed/characters/c115/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c115/match.webp --file=assets/processed/characters/c115/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c116/avatar.webp --file=assets/processed/characters/c116/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c116/gallery.webp --file=assets/processed/characters/c116/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c116/match.webp --file=assets/processed/characters/c116/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c117/avatar.webp --file=assets/processed/characters/c117/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c117/gallery.webp --file=assets/processed/characters/c117/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c117/match.webp --file=assets/processed/characters/c117/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c118/avatar.webp --file=assets/processed/characters/c118/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c118/gallery.webp --file=assets/processed/characters/c118/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c118/match.webp --file=assets/processed/characters/c118/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c119/avatar.webp --file=assets/processed/characters/c119/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c119/gallery.webp --file=assets/processed/characters/c119/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c119/match.webp --file=assets/processed/characters/c119/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c120/avatar.webp --file=assets/processed/characters/c120/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c120/gallery.webp --file=assets/processed/characters/c120/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c120/match.webp --file=assets/processed/characters/c120/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c121/avatar.webp --file=assets/processed/characters/c121/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c121/gallery.webp --file=assets/processed/characters/c121/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c121/match.webp --file=assets/processed/characters/c121/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c122/avatar.webp --file=assets/processed/characters/c122/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c122/gallery.webp --file=assets/processed/characters/c122/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c122/match.webp --file=assets/processed/characters/c122/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c123/avatar.webp --file=assets/processed/characters/c123/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c123/gallery.webp --file=assets/processed/characters/c123/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c123/match.webp --file=assets/processed/characters/c123/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c124/avatar.webp --file=assets/processed/characters/c124/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c124/gallery.webp --file=assets/processed/characters/c124/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c124/match.webp --file=assets/processed/characters/c124/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c125/avatar.webp --file=assets/processed/characters/c125/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c125/gallery.webp --file=assets/processed/characters/c125/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c125/match.webp --file=assets/processed/characters/c125/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c126/avatar.webp --file=assets/processed/characters/c126/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c126/gallery.webp --file=assets/processed/characters/c126/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c126/match.webp --file=assets/processed/characters/c126/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c127/avatar.webp --file=assets/processed/characters/c127/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c127/gallery.webp --file=assets/processed/characters/c127/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c127/match.webp --file=assets/processed/characters/c127/match.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c128/avatar.webp --file=assets/processed/characters/c128/avatar.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c128/gallery.webp --file=assets/processed/characters/c128/gallery.webp --content-type=image/webp --remote
npx wrangler r2 object put fumoe-2026-assets/characters/c128/match.webp --file=assets/processed/characters/c128/match.webp --content-type=image/webp --remote
