import { access, mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import sharp from 'sharp'
import { missingRoster } from './artwork-candidates.ts'
import { artworkOutputs } from '../src/lib/artwork-output.ts'

const root = resolve(import.meta.dirname, '..')
const manifest = JSON.parse(await readFile(resolve(root, 'assets/characters.manifest.json'), 'utf8'))
const rosterSource=await readFile(resolve(root,'src/data/tournament.ts'),'utf8')
const roster=[...rosterSource.matchAll(/\['([^']+)', '([^']+)', '([^']+)'\]/g)].map(([,name,game],index)=>({id:`c${String(index+1).padStart(3,'0')}`,name,game}))
const processedRoot = resolve(root, 'assets/processed/characters')
const results = { generatedAt: new Date().toISOString(), accepted: [], rejected: [], missing:[] }
const variants=Object.fromEntries(Object.entries(artworkOutputs).map(([variant,output])=>[variant,[output.width,output.height]]))

for (const entry of manifest.characters) {
  const checks = []
  for (const [variant, [width, height]] of Object.entries(variants)) {
    const file = resolve(processedRoot, entry.id, `${variant}.webp`)
    try {
      await access(file)
      const info = await sharp(file).metadata()
      const size = await stat(file)
      if (info.width !== width || info.height !== height) throw new Error(`尺寸为 ${info.width}×${info.height}，应为 ${width}×${height}`)
      if (size.size < 12_000) throw new Error(`文件过小：${size.size} bytes`)
      checks.push({ variant, width, height, bytes: size.size })
    } catch (error) { checks.push({ variant, error: error instanceof Error ? error.message : String(error) }) }
  }
  const failed = checks.filter((check) => 'error' in check)
  if (failed.length) results.rejected.push({ id: entry.id, reason: failed.map((check) => `${check.variant}: ${check.error}`).join('; ') })
  else results.accepted.push({ id: entry.id, sourceType: entry.sourceType ?? 'official', sourceUrl: entry.sourceUrl, focus: entry.focus ?? { x: 50, y: 48 }, variants: checks })
}

const ids = results.accepted.map((entry) => entry.id)
results.missing=missingRoster(roster,new Set(ids))
await mkdir(resolve(root, 'assets/reports'), { recursive: true })
await writeFile(resolve(root, 'assets/reports/artwork-quality.json'), `${JSON.stringify(results, null, 2)}\n`)
await writeFile(resolve(root, 'src/data/artwork-index.ts'), `// Generated by scripts/validate-artwork.mjs. Do not hand edit.\nexport const artworkIds = new Set<string>(${JSON.stringify(ids)})\nexport const artworkCoverage = { verified: ${ids.length}, total: 128 }\n`)
console.log(`质量验证通过 ${ids.length}/128 张；拒绝 ${results.rejected.length} 张；仍缺失 ${results.missing.length} 张。`)
